### ISSUE TITLE
Если вы хотите создать аналог константы, то должно быть public static final String UNLIMITED = "Безлимит"

### ISSUE THREAD

**Issue by coursar** [Roman-code37/04.megafon#5]
https://github.com/Roman-code37/04.megafon/blob/abc6ef7cec0cccbf34e1c6fafa9d2dc13952ac63/src/main/java/ru/itpark/Rates/BasicRate.java#L10

**Comment by Roman-code37** [comment]
почему в таком случае используется именно final?

**Comment by coursar** [comment]
потому что `final` позволяет поле проинициализировать только один раз. это и создаёт псевдоэффект константы.

**Comment by Roman-code37** [comment]
ок, понял. Спасибо

**Comment by coursar** [comment]
Единственное, стараются всё-таки писать капсом: `UNLIMITED`, т.к. `Unlimited` очень похоже на обращение к nested-классу.
