### ISSUE TITLE
Надо быть последовательным в названиях - выберите или Rate или Tariff

### ISSUE THREAD

**Issue by coursar** [Roman-code37/04.megafon#8]
https://github.com/Roman-code37/04.megafon/blob/f92bf90c9a644602959c4a0d2afc54727544a7bc/src/main/java/ru/itpark/rate/TureOnTariff.java#L3

**Comment by coursar** [comment]
Кроме того, наверное, должен быть `TurnOnTariff`, а не `TureOnTariff`

**Comment by Roman-code37** [comment]
исправил
